# Generated by Django 2.1.5 on 2019-02-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('liga', models.CharField(max_length=256)),
                ('estado', models.CharField(max_length=256)),
                ('campionatos', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('ubicacion', models.CharField(max_length=256)),
                ('capacidad', models.CharField(max_length=256)),
                ('equipo_local', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('edad', models.CharField(max_length=256)),
                ('estatura', models.CharField(max_length=256)),
                ('nacionalidad', models.CharField(max_length=256)),
                ('equipo', models.CharField(max_length=256)),
                ('universidad', models.CharField(max_length=256)),
                ('posicion', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
