# Generated by Django 2.1.5 on 2019-02-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190207_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='nombre',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='estadio',
            old_name='nombre',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='nombre',
            new_name='content',
        ),
    ]
