# Generated by Django 2.1.5 on 2019-02-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190207_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='content',
            new_name='contentname',
        ),
        migrations.RenameField(
            model_name='estadio',
            old_name='content',
            new_name='contentname',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='content',
            new_name='contentname',
        ),
    ]
